### PR TITLE
reorganize files for release and remove Roosterize-specific data

### PR DESCRIPTION
**Pull request by palmskog**
Please take a look @pengyunie. The removed files/data (on training/groups) should be added to the Roosterize repo. Functions were removed here and can be added back in a possible future corpus release.

### CODE REVIEW

**Comment by palmskog** [comment]
Key changes:

- move all files in `lemmas/lemmas` to `lemmas`
- move all files in `lemmas-filtered/lemmas` to `lemmas-filtered`
- move ` projects-standalone-8.10.yml` to `projects.yml` and remove groups (we only have tiers here)
- remove all files in `data-indexes`, since this is Roosterize-specific
- ~~remove `definitions`, since we don't have kernel terms for definitions (can be added for another release)~~

**Comment by pengyunie** [comment]
> * remove `definitions`, since we don't have kernel terms for definitions (can be added for another release)

Those definitions (currently the names) are used by the sub-tokenizer. Can we keep them here?

Other changes look good to me. Thanks!

**Comment by palmskog** [comment]
> Those definitions (currently the names) are used by the sub-tokenizer. Can we keep them here?

I see, sure, I will add them back right away.

**Comment by palmskog** [comment]
@pengyunie I added back `definitions.json` and adjusted the README.md. Can you take a final look and give go-ahead to merge both this and EngineeringSoftware/roosterize#1?

(This is not set in stone, we can even change releases on GitHub later, but it's nice to wrap up for IJCAR audience.)

**Comment by pengyunie** [comment]
Thanks, they both look good to me.

**Pull request merged**
